/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RankingRouteImport } from './routes/ranking'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as HooksWeeklyPayoutSummaryRouteImport } from './routes/hooks/weekly-payout-summary'
import { Route as ConviteReferralCodeRouteImport } from './routes/convite.$referralCode'
import { Route as AppRulesRouteImport } from './routes/app/rules'
import { Route as AppProfileRouteImport } from './routes/app/profile'
import { Route as AppProductsRouteImport } from './routes/app/products'
import { Route as AppPayoutsRouteImport } from './routes/app/payouts'
import { Route as AppNetworkRouteImport } from './routes/app/network'
import { Route as AppLinkRouteImport } from './routes/app/link'
import { Route as AppLeadsRouteImport } from './routes/app/leads'
import { Route as AppCommissionsRouteImport } from './routes/app/commissions'
import { Route as ApiTrackEventRouteImport } from './routes/api.track-event'
import { Route as ApiProductsRouteImport } from './routes/api.products'
import { Route as ApiLeadsRouteImport } from './routes/api.leads'
import { Route as ApiAffiliatesRouteImport } from './routes/api.affiliates'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AdminRequestsRouteImport } from './routes/admin/requests'
import { Route as AdminProductsRouteImport } from './routes/admin/products'
import { Route as AdminPayoutsRouteImport } from './routes/admin/payouts'
import { Route as AdminNetworkRulesRouteImport } from './routes/admin/network-rules'
import { Route as AdminNetworkCommissionsRouteImport } from './routes/admin/network-commissions'
import { Route as AdminNetworkRouteImport } from './routes/admin/network'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminLeadsRouteImport } from './routes/admin/leads'
import { Route as AdminCommissionsRouteImport } from './routes/admin/commissions'
import { Route as AdminBuyersRouteImport } from './routes/admin/buyers'
import { Route as AdminAuditRouteImport } from './routes/admin/audit'
import { Route as AdminApiRouteImport } from './routes/admin/api'
import { Route as AdminAnalyticsRouteImport } from './routes/admin/analytics'
import { Route as AdminAffiliatesRouteImport } from './routes/admin/affiliates'
import { Route as PProductSlugAffiliateSlugRouteImport } from './routes/p.$productSlug.$affiliateSlug'
import { Route as ApiAffiliatesSlugRouteImport } from './routes/api.affiliates.$slug'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RankingRoute = RankingRouteImport.update({
  id: '/ranking',
  path: '/ranking',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/app/',
  path: '/app/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const HooksWeeklyPayoutSummaryRoute =
  HooksWeeklyPayoutSummaryRouteImport.update({
    id: '/hooks/weekly-payout-summary',
    path: '/hooks/weekly-payout-summary',
    getParentRoute: () => rootRouteImport,
  } as any)
const ConviteReferralCodeRoute = ConviteReferralCodeRouteImport.update({
  id: '/convite/$referralCode',
  path: '/convite/$referralCode',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRulesRoute = AppRulesRouteImport.update({
  id: '/app/rules',
  path: '/app/rules',
  getParentRoute: () => rootRouteImport,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/app/profile',
  path: '/app/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const AppProductsRoute = AppProductsRouteImport.update({
  id: '/app/products',
  path: '/app/products',
  getParentRoute: () => rootRouteImport,
} as any)
const AppPayoutsRoute = AppPayoutsRouteImport.update({
  id: '/app/payouts',
  path: '/app/payouts',
  getParentRoute: () => rootRouteImport,
} as any)
const AppNetworkRoute = AppNetworkRouteImport.update({
  id: '/app/network',
  path: '/app/network',
  getParentRoute: () => rootRouteImport,
} as any)
const AppLinkRoute = AppLinkRouteImport.update({
  id: '/app/link',
  path: '/app/link',
  getParentRoute: () => rootRouteImport,
} as any)
const AppLeadsRoute = AppLeadsRouteImport.update({
  id: '/app/leads',
  path: '/app/leads',
  getParentRoute: () => rootRouteImport,
} as any)
const AppCommissionsRoute = AppCommissionsRouteImport.update({
  id: '/app/commissions',
  path: '/app/commissions',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTrackEventRoute = ApiTrackEventRouteImport.update({
  id: '/api/track-event',
  path: '/api/track-event',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProductsRoute = ApiProductsRouteImport.update({
  id: '/api/products',
  path: '/api/products',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLeadsRoute = ApiLeadsRouteImport.update({
  id: '/api/leads',
  path: '/api/leads',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAffiliatesRoute = ApiAffiliatesRouteImport.update({
  id: '/api/affiliates',
  path: '/api/affiliates',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/admin/settings',
  path: '/admin/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRequestsRoute = AdminRequestsRouteImport.update({
  id: '/admin/requests',
  path: '/admin/requests',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProductsRoute = AdminProductsRouteImport.update({
  id: '/admin/products',
  path: '/admin/products',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPayoutsRoute = AdminPayoutsRouteImport.update({
  id: '/admin/payouts',
  path: '/admin/payouts',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminNetworkRulesRoute = AdminNetworkRulesRouteImport.update({
  id: '/admin/network-rules',
  path: '/admin/network-rules',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminNetworkCommissionsRoute = AdminNetworkCommissionsRouteImport.update({
  id: '/admin/network-commissions',
  path: '/admin/network-commissions',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminNetworkRoute = AdminNetworkRouteImport.update({
  id: '/admin/network',
  path: '/admin/network',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLeadsRoute = AdminLeadsRouteImport.update({
  id: '/admin/leads',
  path: '/admin/leads',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCommissionsRoute = AdminCommissionsRouteImport.update({
  id: '/admin/commissions',
  path: '/admin/commissions',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBuyersRoute = AdminBuyersRouteImport.update({
  id: '/admin/buyers',
  path: '/admin/buyers',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/admin/audit',
  path: '/admin/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminApiRoute = AdminApiRouteImport.update({
  id: '/admin/api',
  path: '/admin/api',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/admin/analytics',
  path: '/admin/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAffiliatesRoute = AdminAffiliatesRouteImport.update({
  id: '/admin/affiliates',
  path: '/admin/affiliates',
  getParentRoute: () => rootRouteImport,
} as any)
const PProductSlugAffiliateSlugRoute =
  PProductSlugAffiliateSlugRouteImport.update({
    id: '/p/$productSlug/$affiliateSlug',
    path: '/p/$productSlug/$affiliateSlug',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAffiliatesSlugRoute = ApiAffiliatesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ApiAffiliatesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/docs': typeof DocsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/ranking': typeof RankingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin/affiliates': typeof AdminAffiliatesRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/api': typeof AdminApiRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/buyers': typeof AdminBuyersRoute
  '/admin/commissions': typeof AdminCommissionsRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/network': typeof AdminNetworkRoute
  '/admin/network-commissions': typeof AdminNetworkCommissionsRoute
  '/admin/network-rules': typeof AdminNetworkRulesRoute
  '/admin/payouts': typeof AdminPayoutsRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/requests': typeof AdminRequestsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/api/affiliates': typeof ApiAffiliatesRouteWithChildren
  '/api/leads': typeof ApiLeadsRoute
  '/api/products': typeof ApiProductsRoute
  '/api/track-event': typeof ApiTrackEventRoute
  '/app/commissions': typeof AppCommissionsRoute
  '/app/leads': typeof AppLeadsRoute
  '/app/link': typeof AppLinkRoute
  '/app/network': typeof AppNetworkRoute
  '/app/payouts': typeof AppPayoutsRoute
  '/app/products': typeof AppProductsRoute
  '/app/profile': typeof AppProfileRoute
  '/app/rules': typeof AppRulesRoute
  '/convite/$referralCode': typeof ConviteReferralCodeRoute
  '/hooks/weekly-payout-summary': typeof HooksWeeklyPayoutSummaryRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
  '/api/affiliates/$slug': typeof ApiAffiliatesSlugRoute
  '/p/$productSlug/$affiliateSlug': typeof PProductSlugAffiliateSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/docs': typeof DocsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/ranking': typeof RankingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin/affiliates': typeof AdminAffiliatesRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/api': typeof AdminApiRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/buyers': typeof AdminBuyersRoute
  '/admin/commissions': typeof AdminCommissionsRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/network': typeof AdminNetworkRoute
  '/admin/network-commissions': typeof AdminNetworkCommissionsRoute
  '/admin/network-rules': typeof AdminNetworkRulesRoute
  '/admin/payouts': typeof AdminPayoutsRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/requests': typeof AdminRequestsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/api/affiliates': typeof ApiAffiliatesRouteWithChildren
  '/api/leads': typeof ApiLeadsRoute
  '/api/products': typeof ApiProductsRoute
  '/api/track-event': typeof ApiTrackEventRoute
  '/app/commissions': typeof AppCommissionsRoute
  '/app/leads': typeof AppLeadsRoute
  '/app/link': typeof AppLinkRoute
  '/app/network': typeof AppNetworkRoute
  '/app/payouts': typeof AppPayoutsRoute
  '/app/products': typeof AppProductsRoute
  '/app/profile': typeof AppProfileRoute
  '/app/rules': typeof AppRulesRoute
  '/convite/$referralCode': typeof ConviteReferralCodeRoute
  '/hooks/weekly-payout-summary': typeof HooksWeeklyPayoutSummaryRoute
  '/admin': typeof AdminIndexRoute
  '/app': typeof AppIndexRoute
  '/api/affiliates/$slug': typeof ApiAffiliatesSlugRoute
  '/p/$productSlug/$affiliateSlug': typeof PProductSlugAffiliateSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/docs': typeof DocsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/ranking': typeof RankingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin/affiliates': typeof AdminAffiliatesRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/api': typeof AdminApiRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/buyers': typeof AdminBuyersRoute
  '/admin/commissions': typeof AdminCommissionsRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/network': typeof AdminNetworkRoute
  '/admin/network-commissions': typeof AdminNetworkCommissionsRoute
  '/admin/network-rules': typeof AdminNetworkRulesRoute
  '/admin/payouts': typeof AdminPayoutsRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/requests': typeof AdminRequestsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/api/affiliates': typeof ApiAffiliatesRouteWithChildren
  '/api/leads': typeof ApiLeadsRoute
  '/api/products': typeof ApiProductsRoute
  '/api/track-event': typeof ApiTrackEventRoute
  '/app/commissions': typeof AppCommissionsRoute
  '/app/leads': typeof AppLeadsRoute
  '/app/link': typeof AppLinkRoute
  '/app/network': typeof AppNetworkRoute
  '/app/payouts': typeof AppPayoutsRoute
  '/app/products': typeof AppProductsRoute
  '/app/profile': typeof AppProfileRoute
  '/app/rules': typeof AppRulesRoute
  '/convite/$referralCode': typeof ConviteReferralCodeRoute
  '/hooks/weekly-payout-summary': typeof HooksWeeklyPayoutSummaryRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
  '/api/affiliates/$slug': typeof ApiAffiliatesSlugRoute
  '/p/$productSlug/$affiliateSlug': typeof PProductSlugAffiliateSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/docs'
    | '/forgot-password'
    | '/login'
    | '/ranking'
    | '/reset-password'
    | '/signup'
    | '/admin/affiliates'
    | '/admin/analytics'
    | '/admin/api'
    | '/admin/audit'
    | '/admin/buyers'
    | '/admin/commissions'
    | '/admin/leads'
    | '/admin/login'
    | '/admin/network'
    | '/admin/network-commissions'
    | '/admin/network-rules'
    | '/admin/payouts'
    | '/admin/products'
    | '/admin/requests'
    | '/admin/settings'
    | '/api/affiliates'
    | '/api/leads'
    | '/api/products'
    | '/api/track-event'
    | '/app/commissions'
    | '/app/leads'
    | '/app/link'
    | '/app/network'
    | '/app/payouts'
    | '/app/products'
    | '/app/profile'
    | '/app/rules'
    | '/convite/$referralCode'
    | '/hooks/weekly-payout-summary'
    | '/admin/'
    | '/app/'
    | '/api/affiliates/$slug'
    | '/p/$productSlug/$affiliateSlug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/docs'
    | '/forgot-password'
    | '/login'
    | '/ranking'
    | '/reset-password'
    | '/signup'
    | '/admin/affiliates'
    | '/admin/analytics'
    | '/admin/api'
    | '/admin/audit'
    | '/admin/buyers'
    | '/admin/commissions'
    | '/admin/leads'
    | '/admin/login'
    | '/admin/network'
    | '/admin/network-commissions'
    | '/admin/network-rules'
    | '/admin/payouts'
    | '/admin/products'
    | '/admin/requests'
    | '/admin/settings'
    | '/api/affiliates'
    | '/api/leads'
    | '/api/products'
    | '/api/track-event'
    | '/app/commissions'
    | '/app/leads'
    | '/app/link'
    | '/app/network'
    | '/app/payouts'
    | '/app/products'
    | '/app/profile'
    | '/app/rules'
    | '/convite/$referralCode'
    | '/hooks/weekly-payout-summary'
    | '/admin'
    | '/app'
    | '/api/affiliates/$slug'
    | '/p/$productSlug/$affiliateSlug'
  id:
    | '__root__'
    | '/'
    | '/docs'
    | '/forgot-password'
    | '/login'
    | '/ranking'
    | '/reset-password'
    | '/signup'
    | '/admin/affiliates'
    | '/admin/analytics'
    | '/admin/api'
    | '/admin/audit'
    | '/admin/buyers'
    | '/admin/commissions'
    | '/admin/leads'
    | '/admin/login'
    | '/admin/network'
    | '/admin/network-commissions'
    | '/admin/network-rules'
    | '/admin/payouts'
    | '/admin/products'
    | '/admin/requests'
    | '/admin/settings'
    | '/api/affiliates'
    | '/api/leads'
    | '/api/products'
    | '/api/track-event'
    | '/app/commissions'
    | '/app/leads'
    | '/app/link'
    | '/app/network'
    | '/app/payouts'
    | '/app/products'
    | '/app/profile'
    | '/app/rules'
    | '/convite/$referralCode'
    | '/hooks/weekly-payout-summary'
    | '/admin/'
    | '/app/'
    | '/api/affiliates/$slug'
    | '/p/$productSlug/$affiliateSlug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DocsRoute: typeof DocsRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  RankingRoute: typeof RankingRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  AdminAffiliatesRoute: typeof AdminAffiliatesRoute
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminApiRoute: typeof AdminApiRoute
  AdminAuditRoute: typeof AdminAuditRoute
  AdminBuyersRoute: typeof AdminBuyersRoute
  AdminCommissionsRoute: typeof AdminCommissionsRoute
  AdminLeadsRoute: typeof AdminLeadsRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminNetworkRoute: typeof AdminNetworkRoute
  AdminNetworkCommissionsRoute: typeof AdminNetworkCommissionsRoute
  AdminNetworkRulesRoute: typeof AdminNetworkRulesRoute
  AdminPayoutsRoute: typeof AdminPayoutsRoute
  AdminProductsRoute: typeof AdminProductsRoute
  AdminRequestsRoute: typeof AdminRequestsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  ApiAffiliatesRoute: typeof ApiAffiliatesRouteWithChildren
  ApiLeadsRoute: typeof ApiLeadsRoute
  ApiProductsRoute: typeof ApiProductsRoute
  ApiTrackEventRoute: typeof ApiTrackEventRoute
  AppCommissionsRoute: typeof AppCommissionsRoute
  AppLeadsRoute: typeof AppLeadsRoute
  AppLinkRoute: typeof AppLinkRoute
  AppNetworkRoute: typeof AppNetworkRoute
  AppPayoutsRoute: typeof AppPayoutsRoute
  AppProductsRoute: typeof AppProductsRoute
  AppProfileRoute: typeof AppProfileRoute
  AppRulesRoute: typeof AppRulesRoute
  ConviteReferralCodeRoute: typeof ConviteReferralCodeRoute
  HooksWeeklyPayoutSummaryRoute: typeof HooksWeeklyPayoutSummaryRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AppIndexRoute: typeof AppIndexRoute
  PProductSlugAffiliateSlugRoute: typeof PProductSlugAffiliateSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ranking': {
      id: '/ranking'
      path: '/ranking'
      fullPath: '/ranking'
      preLoaderRoute: typeof RankingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/app'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hooks/weekly-payout-summary': {
      id: '/hooks/weekly-payout-summary'
      path: '/hooks/weekly-payout-summary'
      fullPath: '/hooks/weekly-payout-summary'
      preLoaderRoute: typeof HooksWeeklyPayoutSummaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/convite/$referralCode': {
      id: '/convite/$referralCode'
      path: '/convite/$referralCode'
      fullPath: '/convite/$referralCode'
      preLoaderRoute: typeof ConviteReferralCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/rules': {
      id: '/app/rules'
      path: '/app/rules'
      fullPath: '/app/rules'
      preLoaderRoute: typeof AppRulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/profile': {
      id: '/app/profile'
      path: '/app/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/products': {
      id: '/app/products'
      path: '/app/products'
      fullPath: '/app/products'
      preLoaderRoute: typeof AppProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/payouts': {
      id: '/app/payouts'
      path: '/app/payouts'
      fullPath: '/app/payouts'
      preLoaderRoute: typeof AppPayoutsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/network': {
      id: '/app/network'
      path: '/app/network'
      fullPath: '/app/network'
      preLoaderRoute: typeof AppNetworkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/link': {
      id: '/app/link'
      path: '/app/link'
      fullPath: '/app/link'
      preLoaderRoute: typeof AppLinkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/leads': {
      id: '/app/leads'
      path: '/app/leads'
      fullPath: '/app/leads'
      preLoaderRoute: typeof AppLeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/commissions': {
      id: '/app/commissions'
      path: '/app/commissions'
      fullPath: '/app/commissions'
      preLoaderRoute: typeof AppCommissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/track-event': {
      id: '/api/track-event'
      path: '/api/track-event'
      fullPath: '/api/track-event'
      preLoaderRoute: typeof ApiTrackEventRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/products': {
      id: '/api/products'
      path: '/api/products'
      fullPath: '/api/products'
      preLoaderRoute: typeof ApiProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/leads': {
      id: '/api/leads'
      path: '/api/leads'
      fullPath: '/api/leads'
      preLoaderRoute: typeof ApiLeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/affiliates': {
      id: '/api/affiliates'
      path: '/api/affiliates'
      fullPath: '/api/affiliates'
      preLoaderRoute: typeof ApiAffiliatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/requests': {
      id: '/admin/requests'
      path: '/admin/requests'
      fullPath: '/admin/requests'
      preLoaderRoute: typeof AdminRequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/products': {
      id: '/admin/products'
      path: '/admin/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/payouts': {
      id: '/admin/payouts'
      path: '/admin/payouts'
      fullPath: '/admin/payouts'
      preLoaderRoute: typeof AdminPayoutsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/network-rules': {
      id: '/admin/network-rules'
      path: '/admin/network-rules'
      fullPath: '/admin/network-rules'
      preLoaderRoute: typeof AdminNetworkRulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/network-commissions': {
      id: '/admin/network-commissions'
      path: '/admin/network-commissions'
      fullPath: '/admin/network-commissions'
      preLoaderRoute: typeof AdminNetworkCommissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/network': {
      id: '/admin/network'
      path: '/admin/network'
      fullPath: '/admin/network'
      preLoaderRoute: typeof AdminNetworkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/leads': {
      id: '/admin/leads'
      path: '/admin/leads'
      fullPath: '/admin/leads'
      preLoaderRoute: typeof AdminLeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/commissions': {
      id: '/admin/commissions'
      path: '/admin/commissions'
      fullPath: '/admin/commissions'
      preLoaderRoute: typeof AdminCommissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/buyers': {
      id: '/admin/buyers'
      path: '/admin/buyers'
      fullPath: '/admin/buyers'
      preLoaderRoute: typeof AdminBuyersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/audit': {
      id: '/admin/audit'
      path: '/admin/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/api': {
      id: '/admin/api'
      path: '/admin/api'
      fullPath: '/admin/api'
      preLoaderRoute: typeof AdminApiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/admin/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/affiliates': {
      id: '/admin/affiliates'
      path: '/admin/affiliates'
      fullPath: '/admin/affiliates'
      preLoaderRoute: typeof AdminAffiliatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$productSlug/$affiliateSlug': {
      id: '/p/$productSlug/$affiliateSlug'
      path: '/p/$productSlug/$affiliateSlug'
      fullPath: '/p/$productSlug/$affiliateSlug'
      preLoaderRoute: typeof PProductSlugAffiliateSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/affiliates/$slug': {
      id: '/api/affiliates/$slug'
      path: '/$slug'
      fullPath: '/api/affiliates/$slug'
      preLoaderRoute: typeof ApiAffiliatesSlugRouteImport
      parentRoute: typeof ApiAffiliatesRoute
    }
  }
}

interface ApiAffiliatesRouteChildren {
  ApiAffiliatesSlugRoute: typeof ApiAffiliatesSlugRoute
}

const ApiAffiliatesRouteChildren: ApiAffiliatesRouteChildren = {
  ApiAffiliatesSlugRoute: ApiAffiliatesSlugRoute,
}

const ApiAffiliatesRouteWithChildren = ApiAffiliatesRoute._addFileChildren(
  ApiAffiliatesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DocsRoute: DocsRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  RankingRoute: RankingRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  AdminAffiliatesRoute: AdminAffiliatesRoute,
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminApiRoute: AdminApiRoute,
  AdminAuditRoute: AdminAuditRoute,
  AdminBuyersRoute: AdminBuyersRoute,
  AdminCommissionsRoute: AdminCommissionsRoute,
  AdminLeadsRoute: AdminLeadsRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminNetworkRoute: AdminNetworkRoute,
  AdminNetworkCommissionsRoute: AdminNetworkCommissionsRoute,
  AdminNetworkRulesRoute: AdminNetworkRulesRoute,
  AdminPayoutsRoute: AdminPayoutsRoute,
  AdminProductsRoute: AdminProductsRoute,
  AdminRequestsRoute: AdminRequestsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  ApiAffiliatesRoute: ApiAffiliatesRouteWithChildren,
  ApiLeadsRoute: ApiLeadsRoute,
  ApiProductsRoute: ApiProductsRoute,
  ApiTrackEventRoute: ApiTrackEventRoute,
  AppCommissionsRoute: AppCommissionsRoute,
  AppLeadsRoute: AppLeadsRoute,
  AppLinkRoute: AppLinkRoute,
  AppNetworkRoute: AppNetworkRoute,
  AppPayoutsRoute: AppPayoutsRoute,
  AppProductsRoute: AppProductsRoute,
  AppProfileRoute: AppProfileRoute,
  AppRulesRoute: AppRulesRoute,
  ConviteReferralCodeRoute: ConviteReferralCodeRoute,
  HooksWeeklyPayoutSummaryRoute: HooksWeeklyPayoutSummaryRoute,
  AdminIndexRoute: AdminIndexRoute,
  AppIndexRoute: AppIndexRoute,
  PProductSlugAffiliateSlugRoute: PProductSlugAffiliateSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
